# Generated by Django 6.0.4 on 2026-05-04 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spots',
            name='body',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='spots',
            name='name_spot',
            field=models.CharField(max_length=200),
        ),
    ]
