# Generated by Django 6.0.4 on 2026-05-05 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skate', '0002_alter_spots_body_alter_spots_name_spot'),
    ]

    operations = [
        migrations.AddField(
            model_name='spots',
            name='image_url',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
