# Generated by Django 6.0.4 on 2026-05-05 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skate', '0003_spots_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spots',
            name='image_url',
            field=models.ImageField(null=True, upload_to='spots/'),
        ),
    ]
