# Generated by Django 6.0.4 on 2026-05-08 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skate', '0005_alter_spots_image_url'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.UniqueConstraint(fields=('user', 'spot'), name='unique_user_spot_rating'),
        ),
    ]
