# Generated by Django 6.0.4 on 2026-04-27 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skate', '0005_alter_spots_created_at_alter_user_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spots',
            old_name='user_id',
            new_name='user',
        ),
    ]
