# Generated by Django 6.0.4 on 2026-04-27 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skate', '0006_rename_user_id_spots_user'),
    ]

    operations = [
    migrations.RunSQL(
        "ALTER TABLE skate_spots ALTER COLUMN created_at TYPE timestamp with time zone USING created_at::interval + CURRENT_DATE;",
    ),
    migrations.AlterField(
        model_name='user',
        name='created_at',
        field=models.DateTimeField(auto_now_add=True),
    ),
]
