# Generated by Django 6.0.4 on 2026-04-27 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skate', '0007_alter_spots_created_at_alter_user_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spots',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
