# Generated by Django 6.0.4 on 2026-04-27 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skate', '0004_alter_spots_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skate.spots')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skate.user')),
            ],
            options={
                'unique_together': {('user', 'spot')},
            },
        ),
    ]
