# Generated by Django 6.0.4 on 2026-04-27 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skate', '0009_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spots',
            name='body',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=200, unique=True),
        ),
    ]
