# Generated by Django 6.0.5 on 2026-05-17 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skate', '0006_alter_rating_unique_together_and_more'),
        ('skate', '0010_alter_spots_body_alter_user_email'),
    ]

    operations = [
    ]
