# Generated by Django 6.0.4 on 2026-04-23 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserView',
        ),
    ]
