# Generated by Django 6.0.4 on 2026-04-23 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_rename_user_userview'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserView',
            new_name='User',
        ),
    ]
