# Generated by Django 6.0.4 on 2026-04-27 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0004_user_created_at_alter_user_email_spots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spots',
            name='created_at',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_created=True, blank=True),
        ),
    ]
